clone_depth: 1

install:
  - git clone --depth=1 https://github.com/nothings/stb.git thirdparty/stb
  - svn co http://svn.code.sf.net/p/utfcpp/code/v2_0/source thirdparty/utf8-cpp

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 9 2008"
  - cmake --build . --config Release
  - dir
  - dir Release
  - appveyor PushArtifact Release/AGSBMFontRenderer.dll
